## This notebook is to normalize the data and prep the tables for the database and the dashboard

In [2]:
import sys
import polars as pl
import pandas as pd

sys.path.append('/Projects/regionintelligence/apn_insights/')

from src.paths import DATA_DIR
# Set display options
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 50)
pd.set_option('display.max_colwidth', None)  # or use a specific number like 100
pd.set_option('display.width', 1000)

In [3]:


pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', lambda x: '%.3f' % x) 

#clean data dir
file_path = DATA_DIR / '2019_RI_LAND_USE.csv'

#df = pl.scan_csv(file_path)

df = pd.read_csv(file_path)

C:\Users\Julian Sotelo\AppData\Local\Temp\ipykernel_17504\463272735.py:9: DtypeWarning: Columns (2,14,17,21,22,24,25,32,33) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

In [4]:
df.shape

(5131098, 75)

In [5]:
## MAP land use codes to land use categories
zoning_dict_2016 = {
    1110: "Single Family Residential",
    1111: "High Density Single Family Residential (9 or more DUs/ac)",
    1112: "Medium Density Single Family Residential (3-8 DUs/ac)",
    1113: "Low Density Single Family Residential (2 or less DUs/ac)",
    1120: "Multi-Family Residential",
    1121: "Mixed Multi-Family Residential",
    1122: "Duplexes, Triplexes and 2- or 3-Unit Condominiums and Townhouses",
    1123: "Low-Rise Apartments, Condominiums, and Townhouses",
    1124: "Medium-Rise Apartments and Condominiums",
    1125: "High-Rise Apartments and Condominiums",
    1130: "Mobile Homes and Trailer Parks",
    1131: "Trailer Parks and Mobile Home Courts, High-Density",
    1132: "Mobile Home Courts and Subdivisions, Low-Density",
    1140: "Mixed Residential",
    1100: "Residential",
    1150: "Rural Residential",
    1210: "General Office Use",
    1211: "Low- and Medium-Rise Major Office Use",
    1212: "High-Rise Major Office Use",
    1213: "Skyscrapers",
    1200: "Commercial and Services",
    1220: "Retail Stores and Commercial Services",
    1221: "Regional Shopping Center",
    1222: "Retail Centers (Non-Strip With Contiguous Interconnected Off-Street Parking)",
    1223: "Retail Strip Development",
    1230: "Other Commercial",
    1231: "Commercial Storage",
    1232: "Commercial Recreation",
    1233: "Hotels and Motels",
    1240: "Public Facilities",
    1241: "Government Offices",
    1242: "Police and Sheriff Stations",
    1243: "Fire Stations",
    1244: "Major Medical Health Care Facilities",
    1245: "Religious Facilities",
    1246: "Other Public Facilities",
    1247: "Public Parking Facilities",
    1250: "Special Use Facilities",
    1251: "Correctional Facilities",
    1252: "Special Care Facilities",
    1253: "Other Special Use Facilities",
    1260: "Educational Institutions",
    1261: "Pre-Schools/Day Care Centers",
    1262: "Elementary Schools",
    1263: "Junior or Intermediate High Schools",
    1264: "Senior High Schools",
    1265: "Colleges and Universities",
    1266: "Trade Schools and Professional Training Facilities",
    1270: "Military Installations",
    1271: "Base (Built-up Area)",
    1272: "Vacant Area",
    1273: "Air Field",
    1274: "Former Base (Built-up Area)",
    1275: "Former Base Vacant Area",
    1276: "Former Base Air Field",
    1300: "Industrial",
    1310: "Light Industrial",
    1311: "Manufacturing, Assembly, and Industrial Services",
    1312: "Motion Picture and Television Studio Lots",
    1313: "Packing Houses and Grain Elevators",
    1314: "Research and Development",
    1320: "Heavy Industrial",
    1321: "Manufacturing",
    1322: "Petroleum Refining and Processing",
    1323: "Open Storage",
    1324: "Major Metal Processing",
    1325: "Chemical Processing",
    1330: "Extraction",
    1331: "Mineral Extraction - Other Than Oil and Gas",
    1332: "Mineral Extraction - Oil and Gas",
    1340: "Wholesaling and Warehousing",
    1400: "Transportation, Communications, and Utilities",
    1410: "Transportation",
    1411: "Airports",
    1412: "Railroads",
    1413: "Freeways and Major Roads",
    1414: "Park-and-Ride Lots",
    1415: "Bus Terminals and Yards",
    1416: "Truck Terminals",
    1417: "Harbor Facilities",
    1418: "Navigation Aids",
    1420: "Communication Facilities",
    1430: "Utility Facilities",
    1431: "Electrical Power Facilities",
    1432: "Solid Waste Disposal Facilities",
    1433: "Liquid Waste Disposal Facilities",
    1434: "Water Storage Facilities",
    1435: "Natural Gas and Petroleum Facilities",
    1436: "Water Transfer Facilities",
    1437: "Improved Flood Waterways and Structures",
    1438: "Mixed Utilities",
    1440: "Maintenance Yards",
    1441: "Bus Yards",
    1442: "Rail Yards",
    1450: "Mixed Transportation",
    1460: "Mixed Transportation and Utility",
    1500: "Mixed Commercial and Industrial",
    1600: "Mixed Residential and Commercial",
    1610: "Residential-Oriented Residential/Commercial Mixed Use",
    1620: "Commercial-Oriented Residential/Commercial Mixed Use",
    1800: "Open Space and Recreation",
    1810: "Golf Courses",
    1820: "Local Parks and Recreation",
    1830: "Regional Parks and Recreation",
    1840: "Cemeteries",
    1850: "Wildlife Preserves and Sanctuaries",
    1860: "Specimen Gardens and Arboreta",
    1870: "Beach Parks",
    1880: "Other Open Space and Recreation",
    1890: "Off-Street Trails",
    2000: "Agriculture",
    2100: "Cropland and Improved Pasture Land",
    2110: "Irrigated Cropland and Improved Pasture Land",
    2120: "Non-Irrigated Cropland and Improved Pasture Land",
    2200: "Orchards and Vineyards",
    2300: "Nurseries",
    2400: "Dairy, Intensive Livestock, and Associated Facilities",
    2500: "Poultry Operations",
    2600: "Other Agriculture",
    2700: "Horse Ranches",
    3000: "Vacant",
    3100: "Vacant Undifferentiated",
    3200: "Abandoned Orchards and Vineyards",
    3300: "Vacant With Limited Improvements",
    3400: "Beaches (Vacant)",
    1900: "Urban Vacant",
    4000: "Water",
    4100: "Water, Undifferentiated",
    4200: "Harbor Water Facilities",
    4300: "Marina Water Facilities",
    4400: "Water Within a Military Installation",
    4500: "Area of Inundation (High Water)",
    7777: "Specific Plan",
    1700: "Under Construction",
    8888: "Undevelopable or Protected Land",
    9999: "Unknown",
    'NaN': 'Unknown'
}

In [6]:
def map_zoning_codes(df, zoning_code_column, zoning_dict, column_name):
    """
    Maps zoning codes to their descriptions in a DataFrame.

    Parameters:
    df (DataFrame): The pandas DataFrame containing the data.
    zoning_code_column (str): The name of the column with zoning codes.
    zoning_dict (dict): The dictionary mapping zoning codes to descriptions.

    Returns:
    DataFrame: The DataFrame with an additional column for zoning descriptions.
    """
    # Convert values to strings, strip whitespaces, and replace non-numeric values with NaN
    df[zoning_code_column] = pd.to_numeric(df[zoning_code_column].astype(str).str.strip(), errors='coerce')

    # Convert non-null values to integers
    df.loc[df[zoning_code_column].notnull(), zoning_code_column] = df[zoning_code_column].dropna().astype('int64')

    # Map the zoning codes to descriptions
    df[column_name] = df[zoning_code_column].map(zoning_dict)

    return df
# Assuming 'zoning_code' is the name of your column with the codes
df = map_zoning_codes(df, 'RI_ZONE_CODE', zoning_dict_2016, 'RI_ZONE_CODE_DESC_2016')
df = map_zoning_codes(df, 'RI_GP_CODE', zoning_dict_2016, 'RI_GP_CODE_DESC_2016')
# Check the result
df

,OID_,RI_PARCEL_ID,APN_RAW_2019,COUNTY_NAME,RI_COUNTY_ID,CITY_NAME,CITY_ID,MULTIPART,STACK,ACREAGE,SLOPE,RI_DEM_GEO_ID_20,APN_DUP,IMPROVEMENT_RATIO,LAND_USE_2019,LAND_USE_SOURCE_2019,RI_UNIQUE_PARCEL_ID_2016,APN,CITY_GP_CODE,RI_GP_CODE,SP_INDEX,CITY_SP_CODE,RI_SP_CODE,CITY_ZONE_CODE,RI_ZONE_CODE,LAND_USE_2016,YEAR,PUBLIC_OWNED,PUB_AGENCY_NAME,PUBLIC_TYPE,PUBLIC_SOURCE,BUILDING_SQFT,EPA_BROWN_NAME,EPA_BROWN_TYPE,FIRE_HAZARD,SEARISE_1_METER,SEARISE_2_METER,FLOOD_PLAIN_ZONE,EQUAKE_ZONE,LIQUAFACTION_ZONE,LANDSLIDE_ZONE,PROTECTED_AREA,RIVER_WETLAND_AREA,WILDLIFE_AREA,CNDDB_RARE_SPECIES_AREA,HABITAT_RESERVE_AREA,WETLAND_AREA,URBANIZED_AREA,UNBUILT_SF,GROCERY_1_MILE,HEALTHCARE_1_MILE,OPENSPACE_1_MILE,OPPORTUNITY_LEVEL,HIGH_QUALITY_TRANSIT_AREA,JOB_CENTER,NEIGHBORHOOD_MOBILITY_AREA,ABSOLUTE_CONSTRAINT,VARIABLE_CONSTRAINT,ENVIRONMENT_JUSTICE_AREA,DISADVANTAGED_COMMUNITY_AREA,COMMUNITY_OF_CONCERN,ADU_SPACE_POSSIBILITY,SETBACK_REDUCTION_ADU,SMALL_ADU_POSSIBILITY,PARKING_EXEMPTION_ADU,SETBACK_SMALL_ADU,SETBACK_PARKING_ADU,SMALL_PARKING_ADU,SETBACK_SMALL_PARKING_ADU,JURISDICTION_LABEL,LAND_USE_CLASS_NAME,Shape_Length,Shape_Area,Centroid_X,Centroid_Y,RI_ZONE_CODE_DESC_2016,RI_GP_CODE_DESC_2016
0,1,250001010001,1010001,Imperial,25,Unincorporated,99999,1,1,643.408,0,60250123011001.000,0.000,NaN,2000,ASSESSOR,250000001.000,001-010-001,R/OS,1800.000,0.000,NaN,NaN,NAT_AMER,9999.000,3000,2019,0,TORRES MARTINEZ INDIAN RES,FEDERAL,NaN,NaN,NaN,NaN,1,0,0,1,0,0,0,1,0,0,0,0,1,0,0.000,0,0,0,,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,Imperial County (Unincorporated),Agriculture,7658.838,3667003.519,-116.077,33.419,Unknown,Open Space and Recreation
1,2,250001010004,1010004,Imperial,25,Unincorporated,99999,1,1,37.865,0,60250123021004.000,0.000,0.000,3000,ASSESSOR,250000002.000,001-010-004,U,9999.000,0.000,NaN,NaN,S-2,1800.000,3000,2019,0,BIA,FEDERAL,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000,1,0,0,,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,Imperial County (Unincorporated),Vacant,1879.184,220696.965,-116.048,33.424,Open Space and Recreation,Unknown
2,3,250001010006,1010006,Imperial,25,Unincorporated,99999,1,1,3.111,0,60250123011006.000,0.000,NaN,3000,ASSESSOR,250000003.000,001-010-006,R/OS,1800.000,0.000,NaN,NaN,NAT_AMER,9999.000,3000,2019,0,TORRES MARTINEZ INDIAN RES,FEDERAL,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000,0,0,0,,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,Imperial County (Unincorporated),Vacant,666.943,18130.958,-116.050,33.416,Unknown,Open Space and Recreation
3,4,250001010015,1010015,Imperial,25,Unincorporated,99999,1,1,19.971,0,60250123011003.000,0.000,0.000,3000,ASSESSOR,250000004.000,001-010-015,R/OS,1800.000,0.000,NaN,NaN,S-2,1800.000,3000,2019,0,BIA,FEDERAL,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000,0,0,0,,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,Imperial County (Unincorporated),Vacant,1448.809,116353.846,-116.053,33.407,Open Space and Recreation,Open Space and Recreation
4,5,250001010017,1010017,Imperial,25,Unincorporated,99999,1,1,643.301,15,60250123011002.000,0.000,0.000,1830,CPAD,250000005.000,001-010-017,R/OS,1800.000,0.000,NaN,NaN,S-2,1800.000,3000,2019,1,California Department of Parks and Recreation,STATE,CPAD,NaN,NaN,NaN,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0.000,0,0,0,,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,Imperial County (Unincorporated),Open Space and Recreation,7652.920,3660071.498,-116.077,33.404,Open Space and Recreation,Open Space and Recreation
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5131093,5131094,1110000006835,vcfcd,Ventura,111,Unincorporated,99999,1,1,0.993,0,61110056021036.000,NaN,NaN,NaN,LU16,1110239525.000,vcfcd,A,2000.000,0.000,NaN,NaN,AE-40 ac,2000.000,NaN,2019,0,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0.000,0,0,0,Moderate Resource,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,Ventura County (Unincorporated),NaN,1229.460,5889.239,-119.033,34.201,Agriculture,Agriculture
5131094,5131095,1110000006836,vcfcd,Ventura,111,Unincorporated,99999,1,1,0.363,0,61110097003027.000,NaN,NaN,1243.000,LU16,1110240138.000,vcfcd,NaN,NaN,0.000,NaN,NaN,NaN,NaN,1243.000,2019,0,NaN,NaN,NaN,413.964,NaN,NaN,1,0,0,0,0,0,0,0,0,1,0,0,0,0,15385.869,0,0,0,Moderate Resource,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,Ventura County (Unincorporated),Facilities,270.359,2178.229,-119.104,34.732,NaN,NaN
5131095,5131096,1110000006837,vcfcd,Ventura,111,Unincorporated,99999,1,1,1.569,0,61110056021036.000,NaN,NaN,NaN,LU16,1110239535.000,vcfcd,A,2000.000,0.000,NaN,NaN,AE-40 ac,2000.000,NaN,2019,0,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,1,0,1,0,0,1,0,0,0,0,1,0.000,0,0,0,Moderate Resource,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,Ventura County (Unincorporated),NaN,1809.583,9304.974,-119.031,34.196,Agriculture,Agriculture
5131096,5131097,1110000006838,vcfcd,Ventura,111,Unincorporated,99999,1,1,3.185,0,61110093002031.000,NaN,NaN,2000.000,FMMP,1110239784.000,vcfcd,A,2000.000,0.000,NaN,NaN,AE-40 ac,2000.000,NaN,2019,0,NaN,NaN,NaN,633.637,NaN,NaN,0,0,0,0,0,1,0,0,1,0,0,0,1,1,138094.008,0,0,0,Low Resource,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,Ventura County (Unincorporated),Agriculture,3439.018,18909.599,-119.114,34.251,Agriculture,Agriculture
5131097,5131098,1110000006839,vcfcd,Ventura,111,Unincorporated,99999,1,1,0.141,0,61110003033035.000,NaN,NaN,NaN,LU16,1110239763.000,vcfcd,A,2000.000,0.000,NaN,NaN,AE-40 ac,2000.000,NaN,2019,0,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,1,0,1,0,0,1,0,0,0,1,0,0.000,1,2,1,Moderate Resource,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,Ventura County (Unincorporated),NaN,142.751,838.393,-118.920,34.386,Agriculture,Agriculture

## Parcel Table

In [7]:
parcel_columns = ['RI_PARCEL_ID', 'LAND_USE_2019', 'LAND_USE_SOURCE_2019', 'LAND_USE_2016', 'LAND_USE_CLASS_NAME', 'APN_RAW_2019', 'APN', 'ACREAGE', 'SLOPE', 'MULTIPART', 'STACK', 'Shape_Length', 'Shape_Area', 'Centroid_X', 'Centroid_Y']
parcel_df = df[parcel_columns]
parcel_df.reset_index(drop=True, inplace=True)

In [8]:
parcel_df

          RI_PARCEL_ID LAND_USE_2019 LAND_USE_SOURCE_2019 LAND_USE_2016        LAND_USE_CLASS_NAME APN_RAW_2019          APN  ACREAGE  SLOPE  MULTIPART  STACK  Shape_Length  Shape_Area  Centroid_X  Centroid_Y
0         250001010001          2000             ASSESSOR          3000                Agriculture      1010001  001-010-001  643.408      0          1      1      7658.838 3667003.519    -116.077      33.419
1         250001010004          3000             ASSESSOR          3000                     Vacant      1010004  001-010-004   37.865      0          1      1      1879.184  220696.965    -116.048      33.424
2         250001010006          3000             ASSESSOR          3000                     Vacant      1010006  001-010-006    3.111      0          1      1       666.943   18130.958    -116.050      33.416
3         250001010015          3000             ASSESSOR          3000                     Vacant      1010015  001-010-015   19.971      0          1      1      1448.809  116353.846    -116.053      33.407
4         250001010017          1830                 CPAD          3000  Open Space and Recreation      1010017  001-010-017  643.301     15          1      1      7652.920 3660071.498    -116.077      33.404
...                ...           ...                  ...           ...                        ...          ...          ...      ...    ...        ...    ...           ...         ...         ...         ...
5131093  1110000006835           NaN                 LU16           NaN                        NaN        vcfcd        vcfcd    0.993      0          1      1      1229.460    5889.239    -119.033      34.201
5131094  1110000006836      1243.000                 LU16      1243.000                 Facilities        vcfcd        vcfcd    0.363      0          1      1       270.359    2178.229    -119.104      34.732
5131095  1110000006837           NaN                 LU16           NaN                        NaN        vcfcd        vcfcd    1.569      0          1      1      1809.583    9304.974    -119.031      34.196
5131096  1110000006838      2000.000                 FMMP           NaN                Agriculture        vcfcd        vcfcd    3.185      0          1      1      3439.018   18909.599    -119.114      34.251
5131097  1110000006839           NaN                 LU16           NaN                        NaN        vcfcd        vcfcd    0.141      0          1      1       142.751     838.393    -118.920      34.386

[5131098 rows x 15 columns]

##  Building Table

In [9]:
building_columns = ['RI_PARCEL_ID', 'UNBUILT_SF', 'BUILDING_SQFT', 'IMPROVEMENT_RATIO', 'ADU_SPACE_POSSIBILITY', 'SETBACK_REDUCTION_ADU', 'SMALL_ADU_POSSIBILITY', 'PARKING_EXEMPTION_ADU', 'SETBACK_SMALL_ADU', 'SETBACK_PARKING_ADU', 'SMALL_PARKING_ADU', 'SETBACK_SMALL_PARKING_ADU']
building_df = df[building_columns]
building_df.reset_index(drop=True, inplace=True)
building_df

          RI_PARCEL_ID  UNBUILT_SF  BUILDING_SQFT  IMPROVEMENT_RATIO  ADU_SPACE_POSSIBILITY  SETBACK_REDUCTION_ADU  SMALL_ADU_POSSIBILITY  PARKING_EXEMPTION_ADU  SETBACK_SMALL_ADU  SETBACK_PARKING_ADU  SMALL_PARKING_ADU  SETBACK_SMALL_PARKING_ADU
0         250001010001       0.000            NaN                NaN                      0                      0                      0                      0                  0                    0                  0                          0
1         250001010004       0.000            NaN              0.000                      0                      0                      0                      0                  0                    0                  0                          0
2         250001010006       0.000            NaN                NaN                      0                      0                      0                      0                  0                    0                  0                          0
3         250001010015       0.000            NaN              0.000                      0                      0                      0                      0                  0                    0                  0                          0
4         250001010017       0.000            NaN              0.000                      0                      0                      0                      0                  0                    0                  0                          0
...                ...         ...            ...                ...                    ...                    ...                    ...                    ...                ...                  ...                ...                        ...
5131093  1110000006835       0.000            NaN                NaN                      0                      0                      0                      0                  0                    0                  0                          0
5131094  1110000006836   15385.869        413.964                NaN                      0                      0                      0                      0                  0                    0                  0                          0
5131095  1110000006837       0.000            NaN                NaN                      0                      0                      0                      0                  0                    0                  0                          0
5131096  1110000006838  138094.008        633.637                NaN                      0                      0                      0                      0                  0                    0                  0                          0
5131097  1110000006839       0.000            NaN                NaN                      0                      0                      0                      0                  0                    0                  0                          0

[5131098 rows x 12 columns]

## City and County Table

In [10]:
city_columns = ['RI_PARCEL_ID', 'CITY_ID', 'CITY_NAME']
city_df = df[city_columns]
city_df.reset_index(drop=True, inplace=True)

In [11]:
county_columns = ['RI_PARCEL_ID', 'RI_COUNTY_ID', 'COUNTY_NAME']
county_df = df[county_columns]
county_df.reset_index(drop=True, inplace=True)

## Community Development Table

In [12]:
commdev_columns = ['RI_PARCEL_ID', 'RI_COUNTY_ID', 'CITY_ID', 'URBANIZED_AREA',
       'GROCERY_1_MILE', 'HEALTHCARE_1_MILE', 'OPENSPACE_1_MILE',
       'OPPORTUNITY_LEVEL', 'HIGH_QUALITY_TRANSIT_AREA', 'JOB_CENTER',
       'NEIGHBORHOOD_MOBILITY_AREA', 'ABSOLUTE_CONSTRAINT',
       'VARIABLE_CONSTRAINT', 'ENVIRONMENT_JUSTICE_AREA',
       'DISADVANTAGED_COMMUNITY_AREA', 'COMMUNITY_OF_CONCERN']
commdev_df = df[commdev_columns]
commdev_df.reset_index(drop=True, inplace=True)

## Environmental Hazards Table

In [13]:
envhaz_columns = ['RI_PARCEL_ID', 'CITY_ID', 'RI_COUNTY_ID', 'FLOOD_PLAIN_ZONE', 'EQUAKE_ZONE', 'FIRE_HAZARD', 'PROTECTED_AREA', 'RIVER_WETLAND_AREA', 'WILDLIFE_AREA', 'WETLAND_AREA', 'CNDDB_RARE_SPECIES_AREA', 'HABITAT_RESERVE_AREA', 'LIQUAFACTION_ZONE', 'LANDSLIDE_ZONE', 'SEARISE_1_METER', 'SEARISE_2_METER']
envhaz_df = df[envhaz_columns]
envhaz_df.reset_index(drop=True, inplace=True)

In [14]:
envhaz_df

          RI_PARCEL_ID  CITY_ID  RI_COUNTY_ID  FLOOD_PLAIN_ZONE  EQUAKE_ZONE  FIRE_HAZARD  PROTECTED_AREA  RIVER_WETLAND_AREA  WILDLIFE_AREA  WETLAND_AREA  CNDDB_RARE_SPECIES_AREA  HABITAT_RESERVE_AREA  LIQUAFACTION_ZONE  LANDSLIDE_ZONE  SEARISE_1_METER  SEARISE_2_METER
0         250001010001    99999            25                 1            0            1               1                   0              0             1                        0                     0                  0               0                0                0
1         250001010004    99999            25                 0            0            0               0                   0              0             0                        0                     0                  0               0                0                0
2         250001010006    99999            25                 0            0            0               0                   0              0             0                        0                     0                  0               0                0                0
3         250001010015    99999            25                 0            0            0               0                   0              0             0                        0                     0                  0               0                0                0
4         250001010017    99999            25                 0            0            1               1                   0              0             1                        0                     0                  0               0                0                0
...                ...      ...           ...               ...          ...          ...             ...                 ...            ...           ...                      ...                   ...                ...             ...              ...              ...
5131093  1110000006835    99999           111                 1            0            0               0                   0              0             0                        0                     0                  0               0                0                0
5131094  1110000006836    99999           111                 0            0            1               0                   0              1             0                        0                     0                  0               0                0                0
5131095  1110000006837    99999           111                 1            0            0               0                   1              0             0                        0                     0                  1               0                0                0
5131096  1110000006838    99999           111                 0            0            0               0                   1              0             1                        0                     0                  1               0                0                0
5131097  1110000006839    99999           111                 1            0            0               0                   1              0             1                        0                     0                  1               0                0                0

[5131098 rows x 16 columns]

## Zone Plan Table

In [15]:
zone_columns = ['RI_PARCEL_ID', 'CITY_ID', 'CITY_GP_CODE', 'CITY_SP_CODE', 'RI_GP_CODE', 'RI_GP_CODE_DESC_2016', 'RI_SP_CODE', 'CITY_ZONE_CODE', 'RI_ZONE_CODE', 'RI_ZONE_CODE_DESC_2016'] 
zone_df = df[zone_columns]
zone_df.reset_index(drop=True, inplace=True)

In [16]:
zone_df

          RI_PARCEL_ID  CITY_ID CITY_GP_CODE CITY_SP_CODE  RI_GP_CODE       RI_GP_CODE_DESC_2016 RI_SP_CODE CITY_ZONE_CODE  RI_ZONE_CODE     RI_ZONE_CODE_DESC_2016
0         250001010001    99999         R/OS          NaN    1800.000  Open Space and Recreation        NaN       NAT_AMER      9999.000                    Unknown
1         250001010004    99999            U          NaN    9999.000                    Unknown        NaN            S-2      1800.000  Open Space and Recreation
2         250001010006    99999         R/OS          NaN    1800.000  Open Space and Recreation        NaN       NAT_AMER      9999.000                    Unknown
3         250001010015    99999         R/OS          NaN    1800.000  Open Space and Recreation        NaN            S-2      1800.000  Open Space and Recreation
4         250001010017    99999         R/OS          NaN    1800.000  Open Space and Recreation        NaN            S-2      1800.000  Open Space and Recreation
...                ...      ...          ...          ...         ...                        ...        ...            ...           ...                        ...
5131093  1110000006835    99999            A          NaN    2000.000                Agriculture        NaN       AE-40 ac      2000.000                Agriculture
5131094  1110000006836    99999          NaN          NaN         NaN                        NaN        NaN            NaN           NaN                        NaN
5131095  1110000006837    99999            A          NaN    2000.000                Agriculture        NaN       AE-40 ac      2000.000                Agriculture
5131096  1110000006838    99999            A          NaN    2000.000                Agriculture        NaN       AE-40 ac      2000.000                Agriculture
5131097  1110000006839    99999            A          NaN    2000.000                Agriculture        NaN       AE-40 ac      2000.000                Agriculture

[5131098 rows x 10 columns]

In [17]:
# Create a boolean mask where False indicates non-int64 types
non_int64_mask = df['APN_RAW_2019'].apply(lambda x: not isinstance(x, int))

# Display rows where 'your_column' is not int64
print("Non-int64 rows:")
df[non_int64_mask]

Non-int64 rows:

,OID_,RI_PARCEL_ID,APN_RAW_2019,COUNTY_NAME,RI_COUNTY_ID,CITY_NAME,CITY_ID,MULTIPART,STACK,ACREAGE,SLOPE,RI_DEM_GEO_ID_20,APN_DUP,IMPROVEMENT_RATIO,LAND_USE_2019,LAND_USE_SOURCE_2019,RI_UNIQUE_PARCEL_ID_2016,APN,CITY_GP_CODE,RI_GP_CODE,SP_INDEX,CITY_SP_CODE,RI_SP_CODE,CITY_ZONE_CODE,RI_ZONE_CODE,LAND_USE_2016,YEAR,PUBLIC_OWNED,PUB_AGENCY_NAME,PUBLIC_TYPE,PUBLIC_SOURCE,BUILDING_SQFT,EPA_BROWN_NAME,EPA_BROWN_TYPE,FIRE_HAZARD,SEARISE_1_METER,SEARISE_2_METER,FLOOD_PLAIN_ZONE,EQUAKE_ZONE,LIQUAFACTION_ZONE,LANDSLIDE_ZONE,PROTECTED_AREA,RIVER_WETLAND_AREA,WILDLIFE_AREA,CNDDB_RARE_SPECIES_AREA,HABITAT_RESERVE_AREA,WETLAND_AREA,URBANIZED_AREA,UNBUILT_SF,GROCERY_1_MILE,HEALTHCARE_1_MILE,OPENSPACE_1_MILE,OPPORTUNITY_LEVEL,HIGH_QUALITY_TRANSIT_AREA,JOB_CENTER,NEIGHBORHOOD_MOBILITY_AREA,ABSOLUTE_CONSTRAINT,VARIABLE_CONSTRAINT,ENVIRONMENT_JUSTICE_AREA,DISADVANTAGED_COMMUNITY_AREA,COMMUNITY_OF_CONCERN,ADU_SPACE_POSSIBILITY,SETBACK_REDUCTION_ADU,SMALL_ADU_POSSIBILITY,PARKING_EXEMPTION_ADU,SETBACK_SMALL_ADU,SETBACK_PARKING_ADU,SMALL_PARKING_ADU,SETBACK_SMALL_PARKING_ADU,JURISDICTION_LABEL,LAND_USE_CLASS_NAME,Shape_Length,Shape_Area,Centroid_X,Centroid_Y,RI_ZONE_CODE_DESC_2016,RI_GP_CODE_DESC_2016
81920,81921,250063071045,63071045.000,Imperial,25,Imperial,36280,1,1,0.091,0,60250110013082.000,0.000,1.071,1110.000,ASSESSOR,250080904.000,063-071-045,LMR,1110.000,0.000,NaN,NaN,PUD,1100.000,1110.000,2019,0,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0.000,0,0,0,Highest Resource,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,Imperial,Single Family Residential,98.721,522.407,-115.567,32.863,Residential,Single Family Residential
81921,81922,250063071046,63071046.000,Imperial,25,Imperial,36280,1,1,0.091,0,60250110013082.000,0.000,3.600,1110.000,ASSESSOR,250080905.000,063-071-046,LMR,1110.000,0.000,NaN,NaN,PUD,1100.000,1110.000,2019,0,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0.000,0,0,0,Highest Resource,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,Imperial,Single Family Residential,98.771,523.205,-115.567,32.863,Residential,Single Family Residential
81922,81923,250063071047,63071047.000,Imperial,25,Imperial,36280,1,1,0.091,0,60250110013082.000,0.000,3.075,1110.000,ASSESSOR,250080906.000,063-071-047,LMR,1110.000,0.000,NaN,NaN,PUD,1100.000,1110.000,2019,0,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0.000,0,0,0,Highest Resource,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,Imperial,Single Family Residential,98.694,523.503,-115.567,32.863,Residential,Single Family Residential
81923,81924,250063071048,63071048.000,Imperial,25,Imperial,36280,1,1,0.092,0,60250110013082.000,0.000,0.831,1110.000,ASSESSOR,250080907.000,063-071-048,LMR,1110.000,0.000,NaN,NaN,PUD,1100.000,1110.000,2019,0,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0.000,0,0,0,Highest Resource,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,Imperial,Single Family Residential,98.980,529.789,-115.567,32.863,Residential,Single Family Residential
81924,81925,250063071049,63071049.000,Imperial,25,Imperial,36280,1,1,0.114,0,60250110013082.000,0.000,4.000,1110.000,ASSESSOR,250080908.000,063-071-049,LMR,1110.000,0.000,NaN,NaN,PUD,1100.000,1110.000,2019,0,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0.000,0,0,0,Highest Resource,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,Imperial,Single Family Residential,104.188,656.329,-115.567,32.863,Residential,Single Family Residential
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5131093,5131094,1110000006835,vcfcd,Ventura,111,Unincorporated,99999,1,1,0.993,0,61110056021036.000,NaN,NaN,NaN,LU16,1110239525.000,vcfcd,A,2000.000,0.000,NaN,NaN,AE-40 ac,2000.000,NaN,2019,0,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0.000,0,0,0,Moderate Resource,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,Ventura County (Unincorporated),NaN,1229.460,5889.239,-119.033,34.201,Agriculture,Agriculture
5131094,5131095,1110000006836,vcfcd,Ventura,111,Unincorporated,99999,1,1,0.363,0,61110097003027.000,NaN,NaN,1243.000,LU16,1110240138.000,vcfcd,NaN,NaN,0.000,NaN,NaN,NaN,NaN,1243.000,2019,0,NaN,NaN,NaN,413.964,NaN,NaN,1,0,0,0,0,0,0,0,0,1,0,0,0,0,15385.869,0,0,0,Moderate Resource,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,Ventura County (Unincorporated),Facilities,270.359,2178.229,-119.104,34.732,NaN,NaN
5131095,5131096,1110000006837,vcfcd,Ventura,111,Unincorporated,99999,1,1,1.569,0,61110056021036.000,NaN,NaN,NaN,LU16,1110239535.000,vcfcd,A,2000.000,0.000,NaN,NaN,AE-40 ac,2000.000,NaN,2019,0,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,1,0,1,0,0,1,0,0,0,0,1,0.000,0,0,0,Moderate Resource,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,Ventura County (Unincorporated),NaN,1809.583,9304.974,-119.031,34.196,Agriculture,Agriculture
5131096,5131097,1110000006838,vcfcd,Ventura,111,Unincorporated,99999,1,1,3.185,0,61110093002031.000,NaN,NaN,2000.000,FMMP,1110239784.000,vcfcd,A,2000.000,0.000,NaN,NaN,AE-40 ac,2000.000,NaN,2019,0,NaN,NaN,NaN,633.637,NaN,NaN,0,0,0,0,0,1,0,0,1,0,0,0,1,1,138094.008,0,0,0,Low Resource,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,Ventura County (Unincorporated),Agriculture,3439.018,18909.599,-119.114,34.251,Agriculture,Agriculture
5131097,5131098,1110000006839,vcfcd,Ventura,111,Unincorporated,99999,1,1,0.141,0,61110003033035.000,NaN,NaN,NaN,LU16,1110239763.000,vcfcd,A,2000.000,0.000,NaN,NaN,AE-40 ac,2000.000,NaN,2019,0,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,1,0,1,0,0,1,0,0,0,1,0,0.000,1,2,1,Moderate Resource,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,Ventura County (Unincorporated),NaN,142.751,838.393,-118.920,34.386,Agriculture,Agriculture

In [18]:
null_mask = df['APN_RAW_2019'].isnull()

# Display rows where 'your_column' is not int64
print("Null rows:")
df[null_mask]

Null rows:

,OID_,RI_PARCEL_ID,APN_RAW_2019,COUNTY_NAME,RI_COUNTY_ID,CITY_NAME,CITY_ID,MULTIPART,STACK,ACREAGE,SLOPE,RI_DEM_GEO_ID_20,APN_DUP,IMPROVEMENT_RATIO,LAND_USE_2019,LAND_USE_SOURCE_2019,RI_UNIQUE_PARCEL_ID_2016,APN,CITY_GP_CODE,RI_GP_CODE,SP_INDEX,CITY_SP_CODE,RI_SP_CODE,CITY_ZONE_CODE,RI_ZONE_CODE,LAND_USE_2016,YEAR,PUBLIC_OWNED,PUB_AGENCY_NAME,PUBLIC_TYPE,PUBLIC_SOURCE,BUILDING_SQFT,EPA_BROWN_NAME,EPA_BROWN_TYPE,FIRE_HAZARD,SEARISE_1_METER,SEARISE_2_METER,FLOOD_PLAIN_ZONE,EQUAKE_ZONE,LIQUAFACTION_ZONE,LANDSLIDE_ZONE,PROTECTED_AREA,RIVER_WETLAND_AREA,WILDLIFE_AREA,CNDDB_RARE_SPECIES_AREA,HABITAT_RESERVE_AREA,WETLAND_AREA,URBANIZED_AREA,UNBUILT_SF,GROCERY_1_MILE,HEALTHCARE_1_MILE,OPENSPACE_1_MILE,OPPORTUNITY_LEVEL,HIGH_QUALITY_TRANSIT_AREA,JOB_CENTER,NEIGHBORHOOD_MOBILITY_AREA,ABSOLUTE_CONSTRAINT,VARIABLE_CONSTRAINT,ENVIRONMENT_JUSTICE_AREA,DISADVANTAGED_COMMUNITY_AREA,COMMUNITY_OF_CONCERN,ADU_SPACE_POSSIBILITY,SETBACK_REDUCTION_ADU,SMALL_ADU_POSSIBILITY,PARKING_EXEMPTION_ADU,SETBACK_SMALL_ADU,SETBACK_PARKING_ADU,SMALL_PARKING_ADU,SETBACK_SMALL_PARKING_ADU,JURISDICTION_LABEL,LAND_USE_CLASS_NAME,Shape_Length,Shape_Area,Centroid_X,Centroid_Y,RI_ZONE_CODE_DESC_2016,RI_GP_CODE_DESC_2016
87023,87024,250000000001,NaN,Imperial,25,Brawley,8058,1,1,0.052,0,60250104023007.000,NaN,NaN,1220.000,LU16,250085912.000,,Commercial,1200.000,0.000,NaN,NaN,C-2,1220.000,1220.000,2019,0,NaN,NaN,NaN,383.094,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1863.637,0,0,0,Moderate Resource,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,Brawley,Commercial and Services,120.171,297.524,-115.516,32.979,Retail Stores and Commercial Services,Commercial and Services
87024,87025,250000000002,NaN,Imperial,25,Brawley,8058,1,1,0.542,0,60250107003000.000,NaN,NaN,1200.000,LU16,250085909.000,,Commercial,1200.000,0.000,NaN,NaN,C-1,1220.000,1200.000,2019,0,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0.000,0,6,0,High Resource,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,Brawley,Commercial and Services,487.262,3124.352,-115.515,32.978,Retail Stores and Commercial Services,Commercial and Services
87025,87026,250000000003,NaN,Imperial,25,Brawley,8058,1,1,0.226,0,60250106005009.000,NaN,NaN,1130.000,LU16,250085919.000,,Medium Density Residential,1120.000,0.000,NaN,NaN,R-3,1120.000,1130.000,2019,0,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0.000,0,0,0,High Resource,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,Brawley,Mobile Homes and Trailer Parks,489.490,1305.036,-115.565,32.960,Multi-Family Residential,Multi-Family Residential
87026,87027,250000000004,NaN,Imperial,25,Brawley,8058,1,1,0.049,0,60250104023007.000,NaN,NaN,1200.000,LU16,250085911.000,,Commercial,1200.000,0.000,NaN,NaN,C-2,1220.000,1200.000,2019,0,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0.000,0,0,0,Moderate Resource,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,Brawley,Commercial and Services,114.384,281.847,-115.516,32.979,Retail Stores and Commercial Services,Commercial and Services
87027,87028,250000000005,NaN,Imperial,25,Brawley,8058,1,1,1.423,0,60250106002023.000,NaN,NaN,3100.000,LU16,250050665.000,048-250-103,Low Density Residential,1110.000,0.000,NaN,NaN,R-1,1112.000,3100.000,2019,0,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0.000,2,31,0,High Resource,0,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0,Brawley,Vacant,393.487,8205.299,-115.539,32.964,Medium Density Single Family Residential (3-8 DUs/ac),Single Family Residential
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4868839,4868840,710000004751,NaN,San Bernardino,71,Yucca Valley,87056,1,1,1.078,5,60710104283008.000,NaN,NaN,1150.000,LU16,710827966.000,,RL-5; RURAL LIVING (1 DU/5 AC),1150.000,0.000,NaN,NaN,R-L-5,1150.000,1150.000,2019,1,"TRANSPORTATION, DEPT OF",STATE,SPI,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0.000,0,0,0,Moderate Resource,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,Yucca Valley,Rural Residential,945.801,6392.100,-116.384,34.153,Rural Residential,Rural Residential
4868840,4868841,710000004752,NaN,San Bernardino,71,Yucca Valley,87056,1,1,0.436,0,60710104283021.000,NaN,NaN,1150.000,LU16,710530341.000,,RL-5; RURAL LIVING (1 DU/5 AC),1150.000,0.000,NaN,NaN,R-L-5,1150.000,1150.000,2019,1,"TRANSPORTATION, DEPT OF",STATE,SPI,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0.000,0,0,0,Moderate Resource,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,Yucca Valley,Rural Residential,483.857,2583.951,-116.377,34.153,Rural Residential,Rural Residential
4868841,4868842,710000004753,NaN,San Bernardino,71,Yucca Valley,87056,1,1,0.227,5,60710104283008.000,NaN,NaN,1150.000,LU16,710530372.000,,RR-2.5; RURAL RESIDENTIAL (1 DU/2.5 AC),1150.000,0.000,NaN,NaN,R-L-2.5,1150.000,1150.000,2019,1,"TRANSPORTATION, DEPT OF",STATE,SPI,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0.000,0,0,0,Moderate Resource,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,Yucca Valley,Rural Residential,265.099,1346.921,-116.384,34.155,Rural Residential,Rural Residential
4868842,4868843,710000004754,NaN,San Bernardino,71,Yucca Valley,87056,1,1,0.478,0,60710104272002.000,NaN,NaN,NaN,LU16,710530310.000,,I; INDUSTRIAL,1300.000,0.000,NaN,NaN,I,1300.000,NaN,2019,1,"TRANSPORTATION, DEPT OF",STATE,SPI,NaN,NaN,NaN,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0.000,0,0,0,Low Resource,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,Yucca Valley,NaN,535.086,2830.337,-116.449,34.123,Industrial,Industrial
4868843,4868844,710000004755,NaN,San Bernardino,71,Yucca Valley,87056,1,1,0.293,0,60710104271025.000,NaN,NaN,1900.000,LU16,710530311.000,,C-S; SERVICE COMMERCIAL,1200.000,0.000,NaN,NaN,R-S-2,1111.000,1900.000,2019,1,"TRANSPORTATION, DEPT OF",STATE,SPI,NaN,NaN,NaN,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0.000,0,0,0,Low Resource,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,Yucca Valley,Vacant,336.882,1733.511,-116.441,34.123,High Density Single Family Residential (9 or more DUs/ac),Commercial and Services

## Identify the mixed column types and fix them

In [19]:
df.columns

Index(['OID_', 'RI_PARCEL_ID', 'APN_RAW_2019', 'COUNTY_NAME', 'RI_COUNTY_ID', 'CITY_NAME', 'CITY_ID', 'MULTIPART', 'STACK', 'ACREAGE', 'SLOPE', 'RI_DEM_GEO_ID_20', 'APN_DUP', 'IMPROVEMENT_RATIO', 'LAND_USE_2019', 'LAND_USE_SOURCE_2019', 'RI_UNIQUE_PARCEL_ID_2016', 'APN', 'CITY_GP_CODE', 'RI_GP_CODE', 'SP_INDEX', 'CITY_SP_CODE', 'RI_SP_CODE', 'CITY_ZONE_CODE', 'RI_ZONE_CODE', 'LAND_USE_2016', 'YEAR', 'PUBLIC_OWNED', 'PUB_AGENCY_NAME', 'PUBLIC_TYPE', 'PUBLIC_SOURCE', 'BUILDING_SQFT', 'EPA_BROWN_NAME', 'EPA_BROWN_TYPE', 'FIRE_HAZARD', 'SEARISE_1_METER', 'SEARISE_2_METER', 'FLOOD_PLAIN_ZONE', 'EQUAKE_ZONE', 'LIQUAFACTION_ZONE', 'LANDSLIDE_ZONE', 'PROTECTED_AREA', 'RIVER_WETLAND_AREA', 'WILDLIFE_AREA', 'CNDDB_RARE_SPECIES_AREA', 'HABITAT_RESERVE_AREA', 'WETLAND_AREA', 'URBANIZED_AREA', 'UNBUILT_SF', 'GROCERY_1_MILE', 'HEALTHCARE_1_MILE', 'OPENSPACE_1_MILE', 'OPPORTUNITY_LEVEL', 'HIGH_QUALITY_TRANSIT_AREA', 'JOB_CENTER', 'NEIGHBORHOOD_MOBILITY_AREA', 'ABSOLUTE_CONSTRAINT',
       'VARIABLE_CONSTRAINT', 'ENVIRONMENT_JUSTICE_AREA', 'DISADVANTAGED_COMMUNITY_AREA', 'COMMUNITY_OF_CONCERN', 'ADU_SPACE_POSSIBILITY', 'SETBACK_REDUCTION_ADU', 'SMALL_ADU_POSSIBILITY', 'PARKING_EXEMPTION_ADU', 'SETBACK_SMALL_ADU', 'SETBACK_PARKING_ADU', 'SMALL_PARKING_ADU', 'SETBACK_SMALL_PARKING_ADU', 'JURISDICTION_LABEL', 'LAND_USE_CLASS_NAME', 'Shape_Length', 'Shape_Area', 'Centroid_X', 'Centroid_Y', 'RI_ZONE_CODE_DESC_2016', 'RI_GP_CODE_DESC_2016'],
      dtype='object')

In [20]:
## columns 2, 14, 17, 21, 22, 24, 25, 32, 33 have mixed types
def mixed_type_columns(df):
    mixed_columns = []
    for column in df.columns:
        if len(df[column].apply(type).unique()) > 1:
            mixed_columns.append(column)
    return mixed_columns

mixed_columns = mixed_type_columns(df)
print("Columns with mixed types:", mixed_columns)

Columns with mixed types: ['APN_RAW_2019', 'LAND_USE_2019', 'LAND_USE_SOURCE_2019', 'APN', 'CITY_GP_CODE', 'CITY_SP_CODE', 'RI_SP_CODE', 'CITY_ZONE_CODE', 'LAND_USE_2016', 'PUB_AGENCY_NAME', 'PUBLIC_TYPE', 'PUBLIC_SOURCE', 'EPA_BROWN_NAME', 'EPA_BROWN_TYPE', 'OPPORTUNITY_LEVEL', 'LAND_USE_CLASS_NAME', 'RI_ZONE_CODE_DESC_2016', 'RI_GP_CODE_DESC_2016']

In [119]:
temp_df = df[['APN_RAW_2019','LAND_USE_2019', 'LAND_USE_SOURCE_2019', 'APN', 'CITY_GP_CODE', 'CITY_SP_CODE', 'RI_SP_CODE', 'CITY_ZONE_CODE', 'LAND_USE_2016', 'PUB_AGENCY_NAME', 'PUBLIC_TYPE', 'PUBLIC_SOURCE', 'EPA_BROWN_NAME', 'EPA_BROWN_TYPE', 'OPPORTUNITY_LEVEL', 'LAND_USE_CLASS_NAME', 'RI_ZONE_CODE_DESC_2016', 'RI_GP_CODE_DESC_2016']]

temp_df

        APN_RAW_2019 LAND_USE_2019 LAND_USE_SOURCE_2019          APN CITY_GP_CODE CITY_SP_CODE RI_SP_CODE CITY_ZONE_CODE LAND_USE_2016                                PUB_AGENCY_NAME PUBLIC_TYPE PUBLIC_SOURCE EPA_BROWN_NAME EPA_BROWN_TYPE  OPPORTUNITY_LEVEL        LAND_USE_CLASS_NAME     RI_ZONE_CODE_DESC_2016       RI_GP_CODE_DESC_2016
0            1010001          2000             ASSESSOR  001-010-001         R/OS          NaN        NaN       NAT_AMER          3000                     TORRES MARTINEZ INDIAN RES     FEDERAL           NaN            NaN            NaN                                   Agriculture                    Unknown  Open Space and Recreation
1            1010004          3000             ASSESSOR  001-010-004            U          NaN        NaN            S-2          3000                                            BIA     FEDERAL           NaN            NaN            NaN                                        Vacant  Open Space and Recreation                    Unknown
2            1010006          3000             ASSESSOR  001-010-006         R/OS          NaN        NaN       NAT_AMER          3000                     TORRES MARTINEZ INDIAN RES     FEDERAL           NaN            NaN            NaN                                        Vacant                    Unknown  Open Space and Recreation
3            1010015          3000             ASSESSOR  001-010-015         R/OS          NaN        NaN            S-2          3000                                            BIA     FEDERAL           NaN            NaN            NaN                                        Vacant  Open Space and Recreation  Open Space and Recreation
4            1010017          1830                 CPAD  001-010-017         R/OS          NaN        NaN            S-2          3000  California Department of Parks and Recreation       STATE          CPAD            NaN            NaN                     Open Space and Recreation  Open Space and Recreation  Open Space and Recreation
...              ...           ...                  ...          ...          ...          ...        ...            ...           ...                                            ...         ...           ...            ...            ...                ...                        ...                        ...                        ...
5131093        vcfcd           NaN                 LU16        vcfcd            A          NaN        NaN       AE-40 ac           NaN                                            NaN         NaN           NaN            NaN            NaN  Moderate Resource                        NaN                Agriculture                Agriculture
5131094        vcfcd      1243.000                 LU16        vcfcd          NaN          NaN        NaN            NaN      1243.000                                            NaN         NaN           NaN            NaN            NaN  Moderate Resource                 Facilities                        NaN                        NaN
5131095        vcfcd           NaN                 LU16        vcfcd            A          NaN        NaN       AE-40 ac           NaN                                            NaN         NaN           NaN            NaN            NaN  Moderate Resource                        NaN                Agriculture                Agriculture
5131096        vcfcd      2000.000                 FMMP        vcfcd            A          NaN        NaN       AE-40 ac           NaN                                            NaN         NaN           NaN            NaN            NaN       Low Resource                Agriculture                Agriculture                Agriculture
5131097        vcfcd           NaN                 LU16        vcfcd            A          NaN        NaN       AE-40 ac           NaN                                            NaN         NaN           NaN            NaN            NaN  Moderate Resource                        NaN                Agriculture                Agriculture

[5131098 rows x 18 columns]

In [120]:
mixed_type_columns(temp_df)

['APN_RAW_2019',
 'LAND_USE_2019',
 'LAND_USE_SOURCE_2019',
 'APN',
 'CITY_GP_CODE',
 'CITY_SP_CODE',
 'RI_SP_CODE',
 'CITY_ZONE_CODE',
 'LAND_USE_2016',
 'PUB_AGENCY_NAME',
 'PUBLIC_TYPE',
 'PUBLIC_SOURCE',
 'EPA_BROWN_NAME',
 'EPA_BROWN_TYPE',
 'OPPORTUNITY_LEVEL',
 'LAND_USE_CLASS_NAME',
 'RI_ZONE_CODE_DESC_2016',
 'RI_GP_CODE_DESC_2016']

In [117]:
## Identify what datatypes are in the column
temp_df.RI_GP_CODE_DESC_2016.apply(type).unique()

array([<class 'str'>, <class 'float'>], dtype=object)

In [118]:
## Print the string values in the column that are not nulL 
temp_df.loc[temp_df.RI_GP_CODE_DESC_2016.apply(type) == float, 'RI_GP_CODE_DESC_2016']  = 'Unknown'

32796      NaN
37022      NaN
37068      NaN
37261      NaN
37338      NaN
          ...
5130881    NaN
5131019    NaN
5131075    NaN
5131077    NaN
5131094    NaN
Name: RI_GP_CODE_DESC_2016, Length: 12116, dtype: object

In [29]:
## Print the string values in the column that are not nulL 
temp_df.loc[temp_df.LAND_USE_CLASS_NAME.apply(type) == int, 'LAND_USE_CLASS_NAME']

Series([], Name: LAND_USE_CLASS_NAME, dtype: object)

## Test the Code

In [121]:
# Replace non-numeric values (like a space ' ') with NaN
temp_df['LAND_USE_2016'] = pd.to_numeric(temp_df['LAND_USE_2016'], errors='coerce')
temp_df['LAND_USE_2016'].fillna(9999, inplace=True)
temp_df['LAND_USE_2016'] = temp_df['LAND_USE_2016'].astype('int64')

## Create logic to fill null values for LAND_USE_2019 with a value from LAND_USE_2016, if available, else 9999
temp_df['LAND_USE_2019'] = pd.to_numeric(temp_df['LAND_USE_2019'], errors='coerce')
temp_df['LAND_USE_2019'].fillna(temp_df['LAND_USE_2016'], inplace=True)
temp_df['LAND_USE_2019'] = temp_df['LAND_USE_2019'].astype('int64')


strings = ['vcfcd', 'opnspc', 'nap', 'drain', 'common_p', 'common-p', 'common']

## Replace the string values with 00 and convert the column to int64
temp_df.APN_RAW_2019.replace(strings, '00', inplace=True)
temp_df.APN_RAW_2019.fillna('000000000', inplace=True)

is_non_numeric = pd.to_numeric(temp_df['APN_RAW_2019'], errors='coerce').isna()
non_numeric_values = temp_df[is_non_numeric]

temp_df.loc[is_non_numeric, 'APN_RAW_2019'] = 0
temp_df.APN_RAW_2019 = temp_df.APN_RAW_2019.astype('int64')




## Replace the null values with 00 and convert the column to int64
temp_df.APN.fillna('00000', inplace=True)
temp_df.APN.replace(strings, '00000', inplace=True)

is_non_numeric = pd.to_numeric(temp_df['APN'], errors='coerce').isna()
non_numeric_values = temp_df[is_non_numeric]

temp_df.loc[is_non_numeric, 'APN'] = 0
temp_df.APN = temp_df.APN.astype('int64')

## Map the LAND_USE_CLASS_NAME to the dictionary zoning_dict_2016
temp_df = map_zoning_codes(temp_df, 'LAND_USE_2019', zoning_dict_2016, 'LAND_USE_CLASS_NAME')


# turn null values into strings called 'Unknown'
temp_df.loc[temp_df['LAND_USE_SOURCE_2019'].apply(type) == float, 'LAND_USE_SOURCE_2019'] = 'Unknown'

# turn null values into strings called 'Unknown'
temp_df.loc[temp_df.CITY_GP_CODE.apply(type) == float, 'CITY_GP_CODE'] = 'Unknown'
temp_df.loc[temp_df.CITY_SP_CODE.apply(type) == float, 'CITY_SP_CODE'] = 'Unknown'

## Print the string values in the column that are not nulL 
temp_df.loc[temp_df.RI_SP_CODE.apply(type) == float, 'RI_SP_CODE'] = 9999
temp_df['RI_SP_CODE'] = pd.to_numeric(temp_df['RI_SP_CODE'], errors='coerce')
temp_df['RI_SP_CODE'].fillna(9999, inplace=True)
temp_df['RI_SP_CODE'] = temp_df['RI_SP_CODE'].astype('int64')

## Print the string values in the column that are not nulL 
temp_df.loc[temp_df.CITY_ZONE_CODE.apply(type) == float, 'CITY_ZONE_CODE'] = 'Unknown'
## Print the string values in the column that are not nulL 
temp_df.loc[temp_df.PUB_AGENCY_NAME.apply(type) == float, 'PUB_AGENCY_NAME'] = 'Unknown'
## Print the string values in the column that are not nulL 
temp_df.loc[temp_df.PUBLIC_TYPE.apply(type) == float, 'PUBLIC_TYPE'] = 'Unknown'
temp_df.loc[temp_df.PUBLIC_SOURCE.apply(type) == float, 'PUBLIC_SOURCE'] = 'Unknown'
temp_df.loc[temp_df.EPA_BROWN_NAME.apply(type) == float, 'EPA_BROWN_NAME'] = 'Unknown'
temp_df.loc[temp_df.EPA_BROWN_TYPE.apply(type) == float, 'EPA_BROWN_TYPE'] = 'Unknown'
temp_df.loc[temp_df.OPPORTUNITY_LEVEL.apply(type) == float, 'OPPORTUNITY_LEVEL'] = 'Unknown'
temp_df.loc[temp_df.RI_ZONE_CODE_DESC_2016.apply(type) == float, 'RI_ZONE_CODE_DESC_2016']  = 'Unknown'
temp_df.loc[temp_df.RI_GP_CODE_DESC_2016.apply(type) == float, 'RI_GP_CODE_DESC_2016']  = 'Unknown'

C:\Users\Julian Sotelo\AppData\Local\Temp\ipykernel_17504\2950884128.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_df['LAND_USE_2016'] = pd.to_numeric(temp_df['LAND_USE_2016'], errors='coerce')
C:\Users\Julian Sotelo\AppData\Local\Temp\ipykernel_17504\2950884128.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_df['LAND_USE_2016'].fillna(9999, inplace=True)
C:\Users\Julian Sotelo\AppData\Local\Temp\ipykernel_17504\2950884128.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_df['LAND_USE_2016'] = temp_df['LAND_USE_2016'].astype('int64')
C:\Users\Julian Sotelo\AppData\Local\Temp\ipykernel_17504\2950884128.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_df['LAND_USE_2019'] = pd.to_numeric(temp_df['LAND_USE_2019'], errors='coerce')
C:\Users\Julian Sotelo\AppData\Local\Temp\ipykernel_17504\2950884128.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_df['LAND_USE_2019'].fillna(temp_df['LAND_USE_2016'], inplace=True)
C:\Users\Julian Sotelo\AppData\Local\Temp\ipykernel_17504\2950884128.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_df['LAND_USE_2019'] = temp_df['LAND_USE_2019'].astype('int64')
C:\Users\Julian Sotelo\AppData\Local\Temp\ipykernel_17504\2950884128.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_df.APN_RAW_2019.replace(strings, '00', inplace=True)
C:\Users\Julian Sotelo\AppData\Local\Temp\ipykernel_17504\2950884128.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_df.APN_RAW_2019.fillna('000000000', inplace=True)
C:\Users\Julian Sotelo\AppData\Local\Temp\ipykernel_17504\2950884128.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_df.APN_RAW_2019 = temp_df.APN_RAW_2019.astype('int64')
C:\Users\Julian Sotelo\AppData\Local\Temp\ipykernel_17504\2950884128.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_df.APN.fillna('00000', inplace=True)
C:\Users\Julian Sotelo\AppData\Local\Temp\ipykernel_17504\2950884128.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_df.APN.replace(strings, '00000', inplace=True)
C:\Users\Julian Sotelo\AppData\Local\Temp\ipykernel_17504\2950884128.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_df.APN = temp_df.APN.astype('int64')
C:\Users\Julian Sotelo\AppData\Local\Temp\ipykernel_17504\2337226320.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[zoning_code_column] = pd.to_numeric(df[zoning_code_column].astype(str).str.strip(), errors='coerce')
C:\Users\Julian Sotelo\AppData\Local\Temp\ipykernel_17504\2337226320.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = df[zoning_code_column].map(zoning_dict)
C:\Users\Julian Sotelo\AppData\Local\Temp\ipykernel_17504\2950884128.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_df['RI_SP_CODE'] = pd.to_numeric(temp_df['RI_SP_CODE'], errors='coerce')
C:\Users\Julian Sotelo\AppData\Local\Temp\ipykernel_17504\2950884128.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_df['RI_SP_CODE'].fillna(9999, inplace=True)
C:\Users\Julian Sotelo\AppData\Local\Temp\ipykernel_17504\2950884128.py:52: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_df['RI_SP_CODE'] = temp_df['RI_SP_CODE'].astype('int64')

In [125]:
temp_df.isnull().sum()

APN_RAW_2019              0
LAND_USE_2019             0
LAND_USE_SOURCE_2019      0
APN                       0
CITY_GP_CODE              0
CITY_SP_CODE              0
RI_SP_CODE                0
CITY_ZONE_CODE            0
LAND_USE_2016             0
PUB_AGENCY_NAME           0
PUBLIC_TYPE               0
PUBLIC_SOURCE             0
EPA_BROWN_NAME            0
EPA_BROWN_TYPE            0
OPPORTUNITY_LEVEL         0
LAND_USE_CLASS_NAME       0
RI_ZONE_CODE_DESC_2016    0
RI_GP_CODE_DESC_2016      0
dtype: int64

## Main Code

In [ ]:
# Replace non-numeric values (like a space ' ') with NaN
df['LAND_USE_2016'] = pd.to_numeric(df['LAND_USE_2016'], errors='coerce')
df['LAND_USE_2016'].fillna(9999, inplace=True)
df['LAND_USE_2016'] = df['LAND_USE_2016'].astype('int64')

## Create logic to fill null values for LAND_USE_2019 with a value from LAND_USE_2016, if available, else 9999
df['LAND_USE_2019'] = pd.to_numeric(df['LAND_USE_2019'], errors='coerce')
df['LAND_USE_2019'].fillna(df['LAND_USE_2016'], inplace=True)
df['LAND_USE_2019'] = df['LAND_USE_2019'].astype('int64')


strings = ['vcfcd', 'opnspc', 'nap', 'drain', 'common_p', 'common-p', 'common']

## Replace the string values with 00 and convert the column to int64
df.APN_RAW_2019.replace(strings, '00', inplace=True)
df.APN_RAW_2019.fillna('000000000', inplace=True)

is_non_numeric = pd.to_numeric(df['APN_RAW_2019'], errors='coerce').isna()
non_numeric_values = df[is_non_numeric]

df.loc[is_non_numeric, 'APN_RAW_2019'] = 0
df.APN_RAW_2019 = df.APN_RAW_2019.astype('int64')




## Replace the null values with 00 and convert the column to int64
df.APN.fillna('00000', inplace=True)
df.APN.replace(strings, '00000', inplace=True)

is_non_numeric = pd.to_numeric(df['APN'], errors='coerce').isna()
non_numeric_values = df[is_non_numeric]

df.loc[is_non_numeric, 'APN'] = 0
df.APN = df.APN.astype('int64')

## Map the LAND_USE_CLASS_NAME to the dictionary zoning_dict_2016
df = map_zoning_codes(df, 'LAND_USE_2019', zoning_dict_2016, 'LAND_USE_CLASS_NAME')


# turn null values into strings called 'Unknown'
df.loc[df['LAND_USE_SOURCE_2019'].apply(type) == float, 'LAND_USE_SOURCE_2019'] = 'Unknown'

# turn null values into strings called 'Unknown'
df.loc[df.CITY_GP_CODE.apply(type) == float, 'CITY_GP_CODE'] = 'Unknown'
df.loc[df.CITY_SP_CODE.apply(type) == float, 'CITY_SP_CODE'] = 'Unknown'

## Print the string values in the column that are not nulL 
df.loc[df.RI_SP_CODE.apply(type) == float, 'RI_SP_CODE'] = 9999
df['RI_SP_CODE'] = pd.to_numeric(df['RI_SP_CODE'], errors='coerce')
df['RI_SP_CODE'].fillna(9999, inplace=True)
df['RI_SP_CODE'] = df['RI_SP_CODE'].astype('int64')

## Print the string values in the column that are not nulL 
df.loc[df.CITY_ZONE_CODE.apply(type) == float, 'CITY_ZONE_CODE'] = 'Unknown'
## Print the string values in the column that are not nulL 
df.loc[df.PUB_AGENCY_NAME.apply(type) == float, 'PUB_AGENCY_NAME'] = 'Unknown'
## Print the string values in the column that are not nulL 
df.loc[df.PUBLIC_TYPE.apply(type) == float, 'PUBLIC_TYPE'] = 'Unknown'
df.loc[df.PUBLIC_SOURCE.apply(type) == float, 'PUBLIC_SOURCE'] = 'Unknown'
df.loc[df.EPA_BROWN_NAME.apply(type) == float, 'EPA_BROWN_NAME'] = 'Unknown'
df.loc[df.EPA_BROWN_TYPE.apply(type) == float, 'EPA_BROWN_TYPE'] = 'Unknown'
df.loc[df.OPPORTUNITY_LEVEL.apply(type) == float, 'OPPORTUNITY_LEVEL'] = 'Unknown'
df.loc[df.RI_ZONE_CODE_DESC_2016.apply(type) == float, 'RI_ZONE_CODE_DESC_2016']  = 'Unknown'
df.loc[df.RI_GP_CODE_DESC_2016.apply(type) == float, 'RI_GP_CODE_DESC_2016']  = 'Unknown'

In [7]:
## Fix the APN Raw 2019 column and APN Column to be int64
contains_zero = (df.APN_RAW_2019 == 00000).any()
print("Does the column contain zero?", contains_zero)

## Identify what datatypes are in the column
df.APN_RAW_2019.apply(type).unique()

## Print the string values in the column that are not nulL 
df.loc[df.APN_RAW_2019.apply(type) == str, 'APN_RAW_2019']

Does the column contain zero? False

2490368    8762028020
2490369    8762029001
2490370    8762029002
2490371    8762029003
2490372    8762029004
              ...
5131093         vcfcd
5131094         vcfcd
5131095         vcfcd
5131096         vcfcd
5131097         vcfcd
Name: APN_RAW_2019, Length: 27358, dtype: object

In [11]:
# identify the rows that are equal to 'vcfcd'
df.loc[df.APN_RAW_2019 == 'vcfcd', 'APN_RAW_2019']

# identify the rows that are equal to 'vcfcd' and make them into an int of 0000000000
df.loc[df.APN_RAW_2019 == 'vcfcd', 'APN_RAW_2019'] = 0000000000

# identify the rows that are equal to 'vcfcd' and make them inta an int of 0000000000
df.loc[df.APN == 'vcfcd', 'APN_RAW_2019'] = 0000000000

In [12]:
# identify the rows that are string 
df.loc[df.APN_RAW_2019.apply(type) == str, 'APN_RAW_2019']

# identify the rows that are equal to 'vcfcd' and make them into an int of 0000000000
df.loc[df.APN_RAW_2019 == 'opnspc', 'APN_RAW_2019'] = 0000000000

# identify the rows that are equal to 'vcfcd' and make them into an int of 0000000000
df.loc[df.APN == 'opnspc', 'APN_RAW_2019'] = 0000000000

In [13]:
# identify the rows that are string 
df.loc[df.APN_RAW_2019.apply(type) == str, 'APN_RAW_2019']

df.loc[df.APN_RAW_2019 == 'nap', 'APN_RAW_2019'] = 0000000000

df.loc[df.APN == 'nap', 'APN_RAW_2019'] = 0000000000

In [14]:
df.loc[df.APN_RAW_2019.apply(type) == str, 'APN_RAW_2019']

df.loc[df.APN_RAW_2019 == 'drain', 'APN_RAW_2019'] = 0000000000

df.loc[df.APN == 'drain', 'APN_RAW_2019'] = 0000000000

In [16]:
df.loc[df.APN_RAW_2019.apply(type) == str, 'APN_RAW_2019']

df.loc[df.APN_RAW_2019 == 'common_p', 'APN_RAW_2019'] = 0000000000

df.loc[df.APN == 'common_p', 'APN_RAW_2019'] = 0000000000

In [18]:
df.loc[df.APN_RAW_2019.apply(type) == str, 'APN_RAW_2019']

df.loc[df.APN_RAW_2019 == 'common-p', 'APN_RAW_2019'] = 0000000000

df.loc[df.APN == 'common-p', 'APN_RAW_2019'] = 0000000000

In [20]:
df.loc[df.APN_RAW_2019.apply(type) == str, 'APN_RAW_2019']

df.loc[df.APN_RAW_2019 == 'common', 'APN_RAW_2019'] = 0000000000

df.loc[df.APN == 'common', 'APN_RAW_2019'] = 0000000000

In [24]:
# Fill null values in APN column with 0000000000
df['APN_RAW_2019'].fillna('0000000000', inplace=True)

# Identify non-numeric values
is_non_numeric = pd.to_numeric(df['APN_RAW_2019'], errors='coerce').isna()
non_numeric_values = df[is_non_numeric]

# Handle non-numeric values (e.g., replace with 0 or handle otherwise)
df.loc[is_non_numeric, 'APN_RAW_2019'] = 0

# Now convert the column to int64
df['APN_RAW_2019'] = df['APN_RAW_2019'].astype('int64')

In [25]:
# FIll null values in APN column with 0000000000
df['APN'].fillna('0000000000', inplace=True)

# Identify non-numeric values
is_non_numeric = pd.to_numeric(df['APN'], errors='coerce').isna()
non_numeric_values = df[is_non_numeric]

# Handle non-numeric values (e.g., replace with 0 or handle otherwise)
df.loc[is_non_numeric, 'APN'] = 0

# Now convert the column to int64
df['APN'] = df['APN'].astype('int64')

In [26]:
# Check the data type of 'APN_RAW_2019' column
data_type = df['APN_RAW_2019'].dtypes
print("Data type of 'APN_RAW_2019':", data_type)

Data type of 'APN_RAW_2019': int64

In [27]:
# Check the data type of 'APN_RAW_2019' column
data_type = df['APN'].dtypes
print("Data type of 'APN':", data_type)

Data type of 'APN': int64

## TEST ETL (Google Cloud Storage) -> (Pandas) -> (Google BigQuery) -> Dashboard

In [1]:
import re 
import sys 
sys.path.append('/Projects/regionintelligence/apn_insights/')
import pandas as pd 
import requests
from src.const import zoning_dict_2016
import pandas as pd
from os import path
import yaml
from pandas import DataFrame
from google.oauth2 import service_account
from google.cloud import bigquery

def grab_apn_from_csv():
    url = 'https://storage.googleapis.com/ri-lnd-use/2019_RI_LAND_USE.csv'
    df = pd.read_csv(url)
    return df, print("done extracting")
df, _ = grab_apn_from_csv()

C:\Users\Julian Sotelo\AppData\Local\Temp\ipykernel_8800\1745229014.py:16: DtypeWarning: Columns (2,14,17,21,22,24,25,32,33) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(url)

done extracting

In [4]:
def clean_transform_csv(df, *args, **kwargs): 
    """
    Template to clean and transform data from the extraction from api
    """
    def map_zoning_codes(df, zoning_code_column, zoning_dict, column_name):
       """
       Maps zoning codes to their descriptions in a DataFrame.

       Parameters:
       df (DataFrame): The pandas DataFrame containing the data.
       zoning_code_column (str): The name of the column with zoning codes.
       zoning_dict (dict): The dictionary mapping zoning codes to descriptions.

       Returns:
       DataFrame: The DataFrame with an additional column for zoning descriptions.
       """
       # Convert values to strings, strip whitespaces, and replace non-numeric values with NaN
       df[zoning_code_column] = pd.to_numeric(df[zoning_code_column].astype(str).str.strip(), errors='coerce')

       # Convert non-null values to integers
       df.loc[df[zoning_code_column].notnull(), zoning_code_column] = df[zoning_code_column].dropna().astype('int64')

       # Map the zoning codes to descriptions
       df[column_name] = df[zoning_code_column].map(zoning_dict)

       return df
    
    # Replace non-numeric values (like a space ' ') with NaN
    df['LAND_USE_2016'] = pd.to_numeric(df['LAND_USE_2016'], errors='coerce')
    df['LAND_USE_2016'].fillna(9999, inplace=True)
    df['LAND_USE_2016'] = df['LAND_USE_2016'].astype('int64')

    ## Create logic to fill null values for LAND_USE_2019 with a value from LAND_USE_2016, if available, else 9999
    df['LAND_USE_2019'] = pd.to_numeric(df['LAND_USE_2019'], errors='coerce')
    df['LAND_USE_2019'].fillna(df['LAND_USE_2016'], inplace=True)
    df['LAND_USE_2019'] = df['LAND_USE_2019'].astype('int64')


    strings = ['vcfcd', 'opnspc', 'nap', 'drain', 'common_p', 'common-p', 'common']

    ## Replace the string values with 00 and convert the column to int64
    df.APN_RAW_2019.replace(strings, '00', inplace=True)
    df.APN_RAW_2019.fillna('000000000', inplace=True)

    is_non_numeric = pd.to_numeric(df['APN_RAW_2019'], errors='coerce').isna()
    non_numeric_values = df[is_non_numeric]

    df.loc[is_non_numeric, 'APN_RAW_2019'] = 0
    df.APN_RAW_2019 = df.APN_RAW_2019.astype('int64')




    ## Replace the null values with 00 and convert the column to int64
    df.APN.fillna('00000', inplace=True)
    df.APN.replace(strings, '00000', inplace=True)

    is_non_numeric = pd.to_numeric(df['APN'], errors='coerce').isna()
    non_numeric_values = df[is_non_numeric]
    
    df.loc[is_non_numeric, 'APN'] = 0
    df.APN = df.APN.astype('int64')
    
    ## Map the LAND_USE_CLASS_NAME to the dictionary zoning_dict_2016
    df = map_zoning_codes(df, 'LAND_USE_2019', zoning_dict_2016, 'LAND_USE_CLASS_NAME')

     # Assuming 'zoning_code' is the name of your column with the codes
    df = map_zoning_codes(df, 'RI_ZONE_CODE', zoning_dict_2016, 'RI_ZONE_CODE_DESC_2016')
    df = map_zoning_codes(df, 'RI_GP_CODE', zoning_dict_2016, 'RI_GP_CODE_DESC_2016')
    
    
    # turn null values into strings called 'Unknown'
    df.loc[df['LAND_USE_SOURCE_2019'].apply(type) == float, 'LAND_USE_SOURCE_2019'] = 'Unknown'
    
    # turn null values into strings called 'Unknown'
    df.loc[df.CITY_GP_CODE.apply(type) == float, 'CITY_GP_CODE'] = 'Unknown'
    df.loc[df.CITY_SP_CODE.apply(type) == float, 'CITY_SP_CODE'] = 'Unknown'
    
    ## Print the string values in the column that are not nulL 
    df.loc[df.RI_SP_CODE.apply(type) == float, 'RI_SP_CODE'] = 9999
    df['RI_SP_CODE'] = pd.to_numeric(df['RI_SP_CODE'], errors='coerce')
    df['RI_SP_CODE'].fillna(9999, inplace=True)
    df['RI_SP_CODE'] = df['RI_SP_CODE'].astype('int64')
    
    ## Print the string values in the column that are not nulL 
    df.loc[df.CITY_ZONE_CODE.apply(type) == float, 'CITY_ZONE_CODE'] = 'Unknown'
    ## Print the string values in the column that are not nulL 
    df.loc[df.PUB_AGENCY_NAME.apply(type) == float, 'PUB_AGENCY_NAME'] = 'Unknown'
    ## Print the string values in the column that are not nulL 
    df.loc[df.PUBLIC_TYPE.apply(type) == float, 'PUBLIC_TYPE'] = 'Unknown'
    df.loc[df.PUBLIC_SOURCE.apply(type) == float, 'PUBLIC_SOURCE'] = 'Unknown'
    df.loc[df.EPA_BROWN_NAME.apply(type) == float, 'EPA_BROWN_NAME'] = 'Unknown'
    df.loc[df.EPA_BROWN_TYPE.apply(type) == float, 'EPA_BROWN_TYPE'] = 'Unknown'
    df.loc[df.OPPORTUNITY_LEVEL.apply(type) == float, 'OPPORTUNITY_LEVEL'] = 'Unknown'
    df.loc[df.RI_ZONE_CODE_DESC_2016.apply(type) == float, 'RI_ZONE_CODE_DESC_2016']  = 'Unknown'
    df.loc[df.RI_GP_CODE_DESC_2016.apply(type) == float, 'RI_GP_CODE_DESC_2016']  = 'Unknown'
    
    
    # Match full_df with df
    full_df = df

    # Separate main df into different tables
    parcel_columns = ['RI_PARCEL_ID', 'LAND_USE_2019', 'LAND_USE_SOURCE_2019', 'LAND_USE_2016', 'LAND_USE_CLASS_NAME', 'APN_RAW_2019', 'APN', 'ACREAGE', 'SLOPE', 'MULTIPART', 'STACK', 'Shape_Length', 'Shape_Area', 'Centroid_X', 'Centroid_Y']
    parcel_df = full_df[parcel_columns]
    parcel_df.reset_index(drop=True, inplace=True)

    # Separate main df into different tables
    building_columns = ['RI_PARCEL_ID', 'UNBUILT_SF', 'BUILDING_SQFT', 'IMPROVEMENT_RATIO', 'ADU_SPACE_POSSIBILITY', 'SETBACK_REDUCTION_ADU', 'SMALL_ADU_POSSIBILITY', 'PARKING_EXEMPTION_ADU', 'SETBACK_SMALL_ADU', 'SETBACK_PARKING_ADU', 'SMALL_PARKING_ADU', 'SETBACK_SMALL_PARKING_ADU']
    building_df = full_df[building_columns]
    building_df.reset_index(drop=True, inplace=True)

    # Separate main df into different tables  
    city_columns = ['RI_PARCEL_ID', 'CITY_ID', 'CITY_NAME']
    city_df = full_df[city_columns]
    city_df.reset_index(drop=True, inplace=True)

    # Separate main df into different tables
    county_columns = ['RI_PARCEL_ID', 'RI_COUNTY_ID', 'COUNTY_NAME']
    county_df = full_df[county_columns]
    county_df.reset_index(drop=True, inplace=True)

    # Separate main df into different tables
    commdev_columns = ['RI_PARCEL_ID', 'RI_COUNTY_ID', 'CITY_ID', 'URBANIZED_AREA', 'GROCERY_1_MILE', 'HEALTHCARE_1_MILE', 'OPENSPACE_1_MILE', 'OPPORTUNITY_LEVEL', 'HIGH_QUALITY_TRANSIT_AREA', 'JOB_CENTER', 'NEIGHBORHOOD_MOBILITY_AREA', 'ABSOLUTE_CONSTRAINT', 'VARIABLE_CONSTRAINT', 'ENVIRONMENT_JUSTICE_AREA', 'DISADVANTAGED_COMMUNITY_AREA', 'COMMUNITY_OF_CONCERN']
    commdev_df = full_df[commdev_columns]
    commdev_df.reset_index(drop=True, inplace=True)

    # Separate main df into different tables
    envhaz_columns = ['RI_PARCEL_ID', 'CITY_ID', 'RI_COUNTY_ID', 'FLOOD_PLAIN_ZONE', 'EQUAKE_ZONE', 'FIRE_HAZARD', 'PROTECTED_AREA', 'RIVER_WETLAND_AREA', 'WILDLIFE_AREA', 'WETLAND_AREA', 'CNDDB_RARE_SPECIES_AREA', 'HABITAT_RESERVE_AREA', 'LIQUAFACTION_ZONE', 'LANDSLIDE_ZONE', 'SEARISE_1_METER', 'SEARISE_2_METER']
    envhaz_df = full_df[envhaz_columns]
    envhaz_df.reset_index(drop=True, inplace=True)

    # Separate main df into different tables
    zone_columns = ['RI_PARCEL_ID', 'CITY_ID', 'CITY_GP_CODE', 'CITY_SP_CODE', 'RI_GP_CODE', 'RI_GP_CODE_DESC_2016', 'RI_SP_CODE', 'CITY_ZONE_CODE', 'RI_ZONE_CODE', 'RI_ZONE_CODE_DESC_2016'] 
    zone_df = full_df[zone_columns]
    zone_df.reset_index(drop=True, inplace=True)

    return {
    "parcel_df": parcel_df.to_dict(orient="dict"),
    "building_df": building_df.to_dict(orient="dict"),
    "city_df": city_df.to_dict(orient="dict"),
    "county_df": county_df.to_dict(orient="dict"),
    "commdev_df": commdev_df.to_dict(orient="dict"),
    "envhaz_df": envhaz_df.to_dict(orient="dict"),
    "zone_df": zone_df.to_dict(orient="dict")
}, print("done transforming")

def test_output(output, *args) -> None:
    """
    Template code for testing the output of the block
    """
    assert output is not None, "Output is undefined"

transformed_data, _= clean_transform_csv(df)

done transforming

In [6]:
from src.paths import PARENT_DIR

def export_data_to_big_query(data, **kwargs) -> None:

    # The path to the config.yaml file.
    config_path = path.join(PARENT_DIR, 'config.yaml')

    # Read the YAML config file.
    with open(config_path, 'r') as f:
        config = yaml.safe_load(f)
    
    # Extract the configuration from the config file.
    bigquery_creds = config['default']['GOOGLE_SERVICE_ACC_KEY']

    # Remove newlines from the private key (if present)
    if 'private_key' in bigquery_creds:
        bigquery_creds['private_key'] = bigquery_creds['private_key'].replace('\\n', '\n')
    
    # Construct the BigQuery client object using the service account info
    credentials = service_account.Credentials.from_service_account_info(
        bigquery_creds,
        scopes=["https://www.googleapis.com/auth/cloud-platform"],
    )
    client = bigquery.Client(credentials=credentials, project=bigquery_creds['project_id'])

    # The dataset ID and table ID in BigQuery.
    dataset_id = 'ri_land_use_dashboard'
   

    for key, inner_dict in data.items():
        # Convert the inner dictionary to a DataFrame
        if isinstance(inner_dict, dict):
            dataframe = pd.DataFrame.from_dict(inner_dict)
            table_id = f"{dataset_id}.{key}"  # Modify this to fit your naming convention
            table_ref = f"{client.project}.{table_id}"

            job_config = bigquery.LoadJobConfig(
                autodetect=True,
                write_disposition=bigquery.WriteDisposition.WRITE_TRUNCATE  # Replace existing table
            )

            # Load the DataFrame to BigQuery
            job = client.load_table_from_dataframe(
                dataframe=dataframe,
                destination=table_ref,
                job_config=job_config
            )

            # Wait for the load job to complete
            job.result()
        else:
            print(f"Warning: The item with key '{key}' is not in the expected format and was skipped.")

    return print("Done exporting")

# Assuming transformed_data is defined earlier
if transformed_data and isinstance(transformed_data, dict):
    export_data_to_big_query(transformed_data)
else:
    print("Error: The data transformation did not return the expected output.")

Done exporting

## TEST ETL (Polars)

## TEST ETL (PySpark)